//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfUser
    {
        public int Id { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime LastLogout { get; set; }
        public int UserId { get; set; }
        public bool IsSuccess { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual User User { get; set; }
    }
}
