//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PassSeries { get; set; }
        public string PassNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string SecurityNumber { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int UserId { get; set; }
        public int InsurancePolicyTypeId { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual InsurancePolicyType InsurancePolicyType { get; set; }
        public virtual User User { get; set; }
    }
}
